### ISSUE TITLE
你不知道的css(三) 

### ISSUE THREAD

**Issue by z2014** [z2014/Blog#11]
1.border
- border-width不支持百分比

2.单位ex（相对字体和字号的单位）
利用ex使图标居中
```css
.icon{
    display: inline-block;
    width: 20px;
    height: 1ex;
    background: url() no-repeat center
}
```
此时调节字体大小，图标都会居中
3.line-height
- line-height就是内联元素的完全高度；是替换元素前一个空白幽灵节点的高度；块级元素无影响
- line-height有数值，百分比值，长度值（em），都是相对于font-size计算得来，如果是数值，子元素继承的就是这个数值，而如果是其他，那么子元素继承的就是计算得来的值
-
